name: skripsyit
description: "MoniFlora Mobile"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.4.3+1
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  firebase_database: ^10.5.4
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  # fuzzy: ^0.5.1
  get: ^4.6.6
  google_sign_in: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  icons_plus: ^5.0.0
  intl: ^0.19.0
  random_forest: ^1.0.0
  shared_preferences: ^2.2.3
  # tflite_flutter: ^0.10.4

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
