// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu9smNLtP-AkAxnQGztYElZVSPJuY6Mw4',
    appId: '1:874509652120:web:b4227bd0446cd0b7f100ed',
    messagingSenderId: '874509652120',
    projectId: 'moniflora-7d3a3',
    authDomain: 'moniflora-7d3a3.firebaseapp.com',
    databaseURL: 'https://moniflora-7d3a3-default-rtdb.firebaseio.com',
    storageBucket: 'moniflora-7d3a3.appspot.com',
    measurementId: 'G-JMMW060MVR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYe_4fdhX4xoQoiT6fi16r4lRoGRqF6lk',
    appId: '1:874509652120:android:6bb866d4e46857ddf100ed',
    messagingSenderId: '874509652120',
    projectId: 'moniflora-7d3a3',
    databaseURL: 'https://moniflora-7d3a3-default-rtdb.firebaseio.com',
    storageBucket: 'moniflora-7d3a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXuGilfeW9KDcN-3YfK1WPBntv4aChuXg',
    appId: '1:874509652120:ios:d29fe1c04559cde1f100ed',
    messagingSenderId: '874509652120',
    projectId: 'moniflora-7d3a3',
    databaseURL: 'https://moniflora-7d3a3-default-rtdb.firebaseio.com',
    storageBucket: 'moniflora-7d3a3.appspot.com',
    iosClientId: '874509652120-otvgfh6kj0ckbj9q8nk9380s1tschod8.apps.googleusercontent.com',
    iosBundleId: 'com.example.skripsyit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXuGilfeW9KDcN-3YfK1WPBntv4aChuXg',
    appId: '1:874509652120:ios:d29fe1c04559cde1f100ed',
    messagingSenderId: '874509652120',
    projectId: 'moniflora-7d3a3',
    databaseURL: 'https://moniflora-7d3a3-default-rtdb.firebaseio.com',
    storageBucket: 'moniflora-7d3a3.appspot.com',
    iosClientId: '874509652120-otvgfh6kj0ckbj9q8nk9380s1tschod8.apps.googleusercontent.com',
    iosBundleId: 'com.example.skripsyit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBu9smNLtP-AkAxnQGztYElZVSPJuY6Mw4',
    appId: '1:874509652120:web:7a5430e33dc80385f100ed',
    messagingSenderId: '874509652120',
    projectId: 'moniflora-7d3a3',
    authDomain: 'moniflora-7d3a3.firebaseapp.com',
    databaseURL: 'https://moniflora-7d3a3-default-rtdb.firebaseio.com',
    storageBucket: 'moniflora-7d3a3.appspot.com',
    measurementId: 'G-QC2KBYL53E',
  );

}